Add recommendations
GordeevGleb/java-filmorate pull request #14
Opened 2024-04-10 14:10 UTC by GordeevGleb

2024-04-10 16:51 UTC, TinyShroom requested changes

2024-04-10 16:51 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbFilmStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Можно удалить блок try catch. Насколько я понимаю, исключение тут не может возникнуть

2024-04-10 16:51 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Если заменить queryForObject на query, то можно избавиться от обработки ошибок в сторидже.

2024-04-10 16:51 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        }
Можно иначе обработать ситуацию, когда похожие пользователи не найдены: например сразу возвращать пустой список фильмов. Если возвращать id того же пользователя, то выполнится два дополнительных запроса к базе, которые вернут пустой список фильмов

2024-04-10 16:51 UTC, TinyShroom commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +
filmService не используется в тестах, можно удалить

2024-04-10 18:22 UTC, GordeevGleb commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        }
исправил

2024-04-10 18:42 UTC, GordeevGleb commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        } catch (EmptyResultDataAccessException e) {
пока не совсем понимаю, как именно это реализовать.
в теории, выглядит так, будто можно переписать этот метод как Optional<Long>, который возвращает  Optional.ofNullable(jdbcTemplate.query(sqlQuery, namedParameters, (ResultSetExtractor<Long>) rs -> rs.getLong(1)));, но, в таком случае, придётся менять структуру самого запроса; в противном случае, поле даже не создаётся при пустом списке рекомендаций.

2024-04-11 04:32 UTC, TinyShroom commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +
А, понялю В UserController появилась зависимость от FilmService. Тогда комментарий можно игнорировать

2024-04-11 04:47 UTC, TinyShroom requested changes

2024-04-11 04:47 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Думаю, можно оставить как было. Нет уверенности, что моё предложение верное)

2024-04-11 04:47 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        }
Учитывая, что метод возвращает не примитив, а Long, возврат null будет более универсальным решением

2024-04-11 04:47 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbFilmStorage.java
> +            return films;
Лишний отступ

2024-04-11 04:47 UTC, TinyShroom commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +
Лишняя пустая строка

2024-04-11 10:10 UTC, TinyShroom requested changes

2024-04-11 10:10 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServiceImpl.java
> +    }
Можно убрать else

2024-04-12 06:48 UTC, closed without merging