feat: add-remove-endpoint
GordeevGleb/java-filmorate pull request #15
Opened 2024-04-10 14:41 UTC by GordeevGleb

2024-04-11 10:34 UTC, adrizhinskaya approved these changes

2024-04-11 19:32 UTC, TinyShroom requested changes

2024-04-11 19:32 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("completion DELETE /film: {} success", id);
Думаю, метод контроллера и сервиса можно назвать просто delete

2024-04-11 19:32 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("completion DELETE /users: success");
Просто delete

2024-04-11 19:32 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +
В сториджах тоже можно просто delete

2024-04-11 19:32 UTC, TinyShroom commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbUserStorage.java
> +        SqlParameterSource namedParameters = new MapSqlParameterSource().addValue("id", id);
Просто delete

2024-04-12 06:37 UTC, TinyShroom approved these changes

2024-04-12 06:45 UTC, merged