Задание 10, Итерация 1
GordeevGleb/java-filmorate pull request #6
Opened 2024-02-28 08:23 UTC by GordeevGleb

2024-02-28 15:12 UTC, Yang-Pi requested changes

2024-02-28 15:12 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Лучше сделать общий класс ErrorHandler, где будет описан мапинг исключений к ResponseEntity

2024-02-28 15:12 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<Map<String, String>> handleUnknownUserException(final NullPointerException e) {
NPE - это не тот тип исключения, который нужно обрабатывать; случаи, где может возникнуть NPE нужно хэндлить проверками на null, if (obj == null)

https://stackoverflow.com/questions/18265940/when-is-it-ok-to-catch-nullpointerexception#:~:text=Effective%20java%20recommend%20that%20we%20shouldn%27t%20catch%20NullPointerException.%20Is%20it%20always%20right%3F

2024-02-28 15:12 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +            throw new NullPointerException("Пользователь с id " + userId + " не найден");
IllegalArgumentException или создать свой FilmNotFoundException

2024-02-28 15:12 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Так ты нарушаешь правило разделения ответственности - контроллер взаимодействует только с сервисом, который в свою очередь уже может работать с хранилищем.

2024-02-28 19:14 UTC, Yang-Pi approved these changes

2024-02-28 19:14 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +public class ErrorHandler {
Имеет смысл добавить хэндлер и для ошибок типа Throwable - те все исключения, и присвоить статус-код 500.

2024-02-28 20:06 UTC, merged

2024-03-12 16:30 UTC, vlad-iv commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilmById(@PathVariable long filmId) throws FilmNotFoundException {
Можно удалить названия модели из всех названий методов

2024-03-12 16:43 UTC, vlad-iv commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +public class InMemoryFilmService implements FilmService {
BaseFilmService

2024-03-12 16:46 UTC, vlad-iv commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +        Film film = filmStorage.getFilmById(filmId);
можно применить подход с Optional

2024-03-12 16:47 UTC, vlad-iv commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
> +        film.addLike(userId);
предлагаю заменить на вызов метода filmStorage.addLike и его реализовать

2024-03-12 16:57 UTC, vlad-iv commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
не является моделью, можно перенести в сторидж