Add database
GordeevGleb/java-filmorate pull request #8
Opened 2024-03-28 14:31 UTC by GordeevGleb

2024-03-28 16:03 UTC, GordeevGleb commented
Здравствуй.
Заранее скажу: я вижу, что сейчас не проходятся некоторые тесты, а так же не до конца дописан тест для FilmDbStorage.
Бьюсь над решением этих задач уже достаточно долго, но никак не могу понять, что именно идёт не так.
Возможно, ты подскажешь. Заранее извиняюсь за заведомо неполное решение задания.

2024-03-30 06:16 UTC, Yang-Pi requested changes

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
>  public class InMemoryFilmStorage implements FilmStorage {
В этом спринте InMemory реализации нужно удалить, тк мигрировали на базу данных

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +package ru.yandex.practicum.filmorate.storage;
Интерфейсы рекомендую на самом деле поместить вместе с dao в одном пакете, потому что это все об одном

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +public class UserDbStorage implements UserStorage, RowMapper<User>, FriendService {
В списке родительских классов, если честно, явно выбивается FriendService) хорошая идея с параметризированным RowMapper, но вот зависимость с интерфейсом сервиса лучше убрать

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                if (!genreStorage.getAllGenres().contains(genre)) {
Запрос к бд в цикле - это то, чего стоит избегать, вообще количество взаимодействий между различными слоями приложения нужно стремиться минимизировать. В это случае достаточно просто запросить все жанры перед циклом

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            genre.setName(genreStorage.getGenreById(genre.getId()).get().getName());
Ты уже знаешь имя после запроса genreStorage.getAllGenres(), поэтому не нужно делать дополнительный запрос, чтобы получить конкретный жанры + этот запрос тоже в цикле

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/film/BaseFilmService.java
> +public class BaseFilmService implements FilmService {
А что значит "Base" в паттерне названия сервисов? FilmServiceImpl более каноничный вариант

2024-03-30 06:16 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/user/BaseUserService.java
> +        User user = userStorage.getUserById(userId1)
Как рекомендация: можно оптимизировать - сделать один запрос к бд с конкретными id, и результат будет считаться положительным, если в ответ получили коллекцию с 2мя объектами

2024-03-31 16:37 UTC, Yang-Pi requested changes

2024-03-31 16:37 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                if (!genreStorage.getAllGenres().contains(genre)) {
Это все еще ошибка, которую нужно исправить

2024-03-31 19:42 UTC, Yang-Pi requested changes

2024-03-31 19:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            genre.setName(genreStorage.getGenreById(genre.getId()).get().getName());
Еще актуально

2024-03-31 19:42 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpaById(film.getMpa().getId()).get());
Ты уже запросил `mpa` на 41й строке, используй эту коллекцию

2024-04-01 16:02 UTC, Yang-Pi approved these changes

2024-04-01 17:05 UTC, merged